name = "MultistartOptimization"
uuid = "3933049c-43be-478e-a8bb-6e0f7fd53575"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[compat]
julia = "^1.3"
ArgCheck = "^1"
DocStringExtensions = "^0.8"
NLopt = "^0.5"
Parameters = "^0.12"
Sobol = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
